spring:
  application:
    name: user-repository
  datasource:
    url: jdbc:mariadb://localhost:3306/assessment_management
    username: root
    password: true
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    httpclient.wire: DEBUG
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
    
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:5002/eureka
server:
  port: 7091